spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/edu_spring
    username: edu
    password: edu1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: mySecretKeyForBoardProjectJwtTokenGeneration1234567890abcdef
  expiration: 86400000

server:
  port: 8080
